### ISSUE TITLE
the application crashes when trying to change the font

### ISSUE THREAD

**Issue by ZetaMap** [xgouchet/Ted#52]
Version: 1.8.1

Crash error:
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.xgouchet.texteditor/fr.xgouchet.texteditor.TedFontActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
	at fr.xgouchet.texteditor.TedFontActivity.onCreate(TedFontActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:6868)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	... 9 more

**Comment by ZetaMap** [comment]
This issue is useless since the project is dead =/
